[programs.localnet]
solana_twitter = "BNMV2mLrcwJ46QZ8k7TwEC1qp4NzR1EK77qabYdsjtan"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/lazar/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
